# -*- coding: utf-8 -*-
"""Ejercicios POO 23/2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ql-PGRnJg4byV4eujWaD95NVRIGtFrp

Una clase es como un plano que define cómo se crean los objetos, pero un objeto es una instancia creada a partir de esa plantilla y tiene sus propios valores y comportamiento. Las clases proporcionan estructura y comportamiento, y los objetos representan datos específicos y pueden realizar acciones específicas definidas por la clase.

Se utiliza como primer argumento en los métodos de Python para referirse a la instancia actual de la clase, permitiendo así el acceso a los atributos y métodos de esa instancia y siguiendo la convención establecida en la comunidad de Python

Un constructor en Python es un método especial dentro de una clase que se llama automáticamente cuando se crea una nueva instancia de esa clase. En Python, el constructor se define utilizando el método __init__(). Este método se utiliza para inicializar los atributos de la instancia recién creada.

Las principales diferencias es que una clase es como un plano que define cómo se crean los objetos, pero un objeto es una instancia creada a partir de esa plantilla y tiene sus propios valores y comportamiento. Las clases proporcionan estructura y comportamiento, y los objetos representan datos específicos y pueden realizar acciones específicas definidas por la clase.La diferencia entre los atributos de clase y los atributos de instancia en Python es su alcance y comportamiento común. Los atributos de clase son compartidos por todas las instancias de una clase, mientras que los atributos de instancia son únicos para cada instancia.
"""

import matplotlib.pyplot as plt

class Punto():
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def plot(self):
        plt.scatter(self.x, self.y, color='red', marker='o')
        plt.xlabel('X-axis')
        plt.ylabel('Y-axis')
        plt.title('Gráfica del punto')
        plt.grid(True)
        plt.show()

punto = Punto(1, 6) #Acabamos de construir al (1, 6)

punto.plot()

"""Aqui ingresamos a la funcion punto para definir ñas coordenadas x y y para graficar un punto"""

class Dante(): #Creamos una clase
#Creamos una definicion
    def __init__(self, precio, producto):
        self.precio = precio
        self.producto = producto

#Creamos una definicion
class ejercicio(Dante):
    def __init__(self, precio, producto, descuento):
        super().__init__(precio, producto)
        self.descuento = descuento
#Creamos una definicion
    def porcentaje(self, descuento):
      if descuento == "descuento":
        print("Su descuento es del 40%")
      else:
          print("El producto no tiene descuento")