# -*- coding: utf-8 -*-
"""POO_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCmaVVe6SJqxFuoJAB3ZRYWAasmZ-e5n
"""

# Vamos a generar una lista vacia

L = []

range(10)

for i in range(10):
 print(i)

"""range(0,10)"""

L = [1, 2, 3, 4]
L

L.append(5)
L

for i in range(10)
  print(1)

type([ ])

"""list"""

len([2, 4, 6, 8])

Pares = [i for i in range(1,100)]
Pares

Odd = [i for i in range(1,101) if i%2==1]
Odd

import numpy as np

import random

# Generar 100 números aleatorios del 1 al 10
numeros_aleatorios = [random.randint(1, 10) for _ in range(100)]

# Filtrar solo los números pares
numeros_pares = [num for num in numeros_aleatorios if num % 2 == 0]

# Imprimir los números generados y los pares
print("Números generados:", numeros_aleatorios)
print("Números pares:", numeros_pares)