# -*- coding: utf-8 -*-
"""POO_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l5ELT05FNcMzI3c42lCB5mV5WWmLeOtw
"""

import numpy as np

np.random.seed(1)

np.random.randint(1, 21, size=15)

L = [i for i in np.random.randint(1, 21, size=40) if i%2==0]
L.sort()
L

L.pop(1)

L.remove(4)
L

L +[4]

L

L.pop(3)

L_arreglo = np.array(L)
L_arreglo

L_arreglo.reshape(3,3)

L_arreglo.reshape(9, 1)