# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EeQQXf0C_b8JNXROEdvEoZoPeyC8waip
"""

def Perimetro(b, l)
p=(b*2)+l
return p

Perimetro(2, 8)

def es_par_o_impar(numero):
    if numero % 2 == 0:
        return "El número es par."
    else:
        return "El número es impar."

numero = int(input("Ingresa un número: "))
print(es_par_o_impar(numero))

numero = int(input("Introduce un número para verificar si es perfecto: "))
if es_numero_perfecto(numero):
    print(f"{numero} es un número perfecto.")
else:
    print(f"{numero} no es un número perfecto.")